version: "3"
services:
  inkydash:
    image: clairesrc/inkydash
    container_name: inkydash
    ports:
      - 8080:5000
    volumes: 
      - ./credentials:/root/.credentials
      - ./config:/inkydash/config
    environment:
      - OPENWEATHERMAP_WEATHER_API_SECRET=${OPENWEATHERMAP_WEATHER_API_SECRET}
      - TZ=${TZ}
    restart: unless-stopped
  inkydash-frontend:
    image: clairesrc/inkydash-frontend
    container_name: inkydash-frontend
    restart: unless-stopped
    privileged: true
    environment:
      - INKYDASH_THEME=${INKYDASH_THEME}
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/ttyAMA0:/dev/ttyAMA0
    cap_add:
      - SYS_RAWIO
