services:
  inkydash-server:
    image: clairesrc/inkydash
    container_name: inkydash-server
    ports:
      - 8080:5000
    environment:
      - OPENWEATHERMAP_WEATHER_API_SECRET=${OPENWEATHERMAP_WEATHER_API_SECRET} # set in .env
    volumes: 
      - ./inkydash-credentials:/root/.credentials
      - ./inkydash-config:/inkydash/config
      - ./inkydash-cache:/inkydash/cache
    restart: unless-stopped
