version: "3"
services:
  inkydash:
    image: clairesrc/inkydash
    container_name: inkydash
    ports:
      - 8080:5000
    volumes: 
      - ./inkydash-credentials:/root/.credentials
      - ./inkydash-config:/inkydash/config
      - ./inkydash-cache:/inkydash/cache
    restart: unless-stopped
