# Use this to change widget order or disable ones you don't want
modules = ["freebusy", "time", "weather"]

[time]
format = "%I:%M %p"

[freebusy]
free_indicator = "FREE"
meeting_buffer = 5 # extra minutes before meeting starts to count as "busy"

[weather]
units = "imperial" # metric/imperial

